
lenguaje: node_js
node_js: 
    - "13.12.0"

before_install: cd ./tu-guia-travis
    
cache:
    directories: 
        - ./tu-guia-travis/node_modules
install:
     - npm install
before_script:
    - npm run-script build
    — npm install -g ionic
script: 
    — ionic build --prod -- --base-href=www
    - npm run test:ci -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox 
       
    deploy:
        provider:
         skip_cleanup: true:
        github_token: $GITHUB_TOKEN
        local_dir: www
        on:
            branch: master


       
                