
    lenguaje: node_js
    node_js: 
        - "13.12.0"
    
    branches:
     only:
     — master
     install:
        - npm install
    before_script:
     — npm install -g ionic
     — npm ci 
    script:
     - npm run-script build


    deploy:
     provider: pages
     skip-cleanup: true
     github-token: $GITHUB_TOKEN 
     keep-history: true
     on:
       branch: master
     local_dir: /app/www


       
                