
    lenguaje: node_js
    node_js: 
        - "13.12.0"
 
    branches:
     only:
     — master
     install:
        - npm install
    before_script:
     — npm install -g ionic
     — npm ci 
    script:
     - npm run-script build




       
                