lenguaje: node_js
node_js: 
    - "13.12.0"

before_install: cd ./tu-guia-travis
cache:
    directories: 
        - ./tu-guia-travis/node_modules
install:
     -npm install
script: 
    - npm run-script build
    



