lenguaje: node_js
node_js: 
    - "13.12.0"

branches:
        only:
        — master

before_install: cd ./tu-guia-travis
cache:
    directories: 
        - ./tu-guia-travis/node_modules
install:
     - npm install

   

before_script:
            — npm install -g ionic
            — npm ci 
                script:
                    — ionic build  --prod 
           
    
deploy:
        provider: pages
        skip-cleanup: true
        github_token: $GITHUB_TOKEN
        keep-history: true
        on:
            branch: master
          local_dir: tu-guia-travis/www
           
          
           
               
